// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9llH1GtDQJpKyiv8rk5GahSZK9_hFzYs',
    appId: '1:226640418465:web:bfca06186dbb1adcb182e0',
    messagingSenderId: '226640418465',
    projectId: 'clean-auth-riverpod',
    authDomain: 'clean-auth-riverpod.firebaseapp.com',
    storageBucket: 'clean-auth-riverpod.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5gNlKP4UOfQ2PH-DSLVBVicPPo3LG71c',
    appId: '1:226640418465:android:94071e0d89cf0ee8b182e0',
    messagingSenderId: '226640418465',
    projectId: 'clean-auth-riverpod',
    storageBucket: 'clean-auth-riverpod.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCO5jotS1i4z4CmVkyQpROWSvRjRxBlhVA',
    appId: '1:226640418465:ios:3545341bffe5f1f2b182e0',
    messagingSenderId: '226640418465',
    projectId: 'clean-auth-riverpod',
    storageBucket: 'clean-auth-riverpod.appspot.com',
    iosClientId: '226640418465-pormj02s5dnouf8e7o6pq2ftmovipqtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthRiverpod',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCO5jotS1i4z4CmVkyQpROWSvRjRxBlhVA',
    appId: '1:226640418465:ios:3545341bffe5f1f2b182e0',
    messagingSenderId: '226640418465',
    projectId: 'clean-auth-riverpod',
    storageBucket: 'clean-auth-riverpod.appspot.com',
    iosClientId: '226640418465-pormj02s5dnouf8e7o6pq2ftmovipqtk.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseAuthRiverpod',
  );
}
